// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.6
// Project name: SmartWatch

#include "../ui.h"

void ui_Screen3_screen_init(void)
{
    ui_Screen3 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen3, lv_color_hex(0x040404), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel1 = lv_obj_create(ui_Screen3);
    lv_obj_set_width(ui_Panel1, 180);
    lv_obj_set_height(ui_Panel1, 170);
    lv_obj_set_x(ui_Panel1, -80);
    lv_obj_set_y(ui_Panel1, -120);
    lv_obj_set_align(ui_Panel1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_majia = lv_img_create(ui_Panel1);
    lv_img_set_src(ui_majia, &ui_img_812553787);
    lv_obj_set_width(ui_majia, LV_SIZE_CONTENT);   /// 80
    lv_obj_set_height(ui_majia, LV_SIZE_CONTENT);    /// 104
    lv_obj_set_align(ui_majia, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_majia, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_majia, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_data = lv_obj_create(ui_Screen3);
    lv_obj_set_width(ui_data, 340);
    lv_obj_set_height(ui_data, 230);
    lv_obj_set_x(ui_data, 0);
    lv_obj_set_y(ui_data, 90);
    lv_obj_set_align(ui_data, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_data, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel7 = lv_obj_create(ui_data);
    lv_obj_set_width(ui_Panel7, 150);
    lv_obj_set_height(ui_Panel7, 110);
    lv_obj_set_x(ui_Panel7, -85);
    lv_obj_set_y(ui_Panel7, -50);
    lv_obj_set_align(ui_Panel7, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel7, lv_color_hex(0x00FFB3), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image2 = lv_img_create(ui_Panel7);
    lv_img_set_src(ui_Image2, &ui_img_airpump_png);
    lv_obj_set_width(ui_Image2, LV_SIZE_CONTENT);   /// 40
    lv_obj_set_height(ui_Image2, LV_SIZE_CONTENT);    /// 40
    lv_obj_set_align(ui_Image2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image5 = lv_img_create(ui_Panel7);
    lv_img_set_src(ui_Image5, &ui_img_airpressure_png);
    lv_obj_set_width(ui_Image5, LV_SIZE_CONTENT);   /// 20
    lv_obj_set_height(ui_Image5, LV_SIZE_CONTENT);    /// 20
    lv_obj_set_x(ui_Image5, 35);
    lv_obj_set_y(ui_Image5, -26);
    lv_obj_set_align(ui_Image5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image5, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Image5, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label2 = lv_label_create(ui_Panel7);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 2
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 2
    lv_obj_set_x(ui_Label2, -15);
    lv_obj_set_y(ui_Label2, 30);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "49.7");
    lv_obj_set_style_text_color(ui_Label2, lv_color_hex(0xF5F5F5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label4 = lv_label_create(ui_Panel7);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 2
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 2
    lv_obj_set_x(ui_Label4, 20);
    lv_obj_set_y(ui_Label4, 30);
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "Mpa");
    lv_obj_set_style_text_color(ui_Label4, lv_color_hex(0xF5F5F5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel6 = lv_obj_create(ui_data);
    lv_obj_set_width(ui_Panel6, 150);
    lv_obj_set_height(ui_Panel6, 110);
    lv_obj_set_x(ui_Panel6, 85);
    lv_obj_set_y(ui_Panel6, -50);
    lv_obj_set_align(ui_Panel6, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel6, lv_color_hex(0x4AFFF6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image7 = lv_img_create(ui_Panel6);
    lv_img_set_src(ui_Image7, &ui_img_zuobiao_png);
    lv_obj_set_width(ui_Image7, LV_SIZE_CONTENT);   /// 40
    lv_obj_set_height(ui_Image7, LV_SIZE_CONTENT);    /// 40
    lv_obj_set_align(ui_Image7, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image7, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image8 = lv_img_create(ui_Panel6);
    lv_img_set_src(ui_Image8, &ui_img_lifang_png);
    lv_obj_set_width(ui_Image8, LV_SIZE_CONTENT);   /// 20
    lv_obj_set_height(ui_Image8, LV_SIZE_CONTENT);    /// 20
    lv_obj_set_x(ui_Image8, 39);
    lv_obj_set_y(ui_Image8, -27);
    lv_obj_set_align(ui_Image8, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image8, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label7 = lv_label_create(ui_Panel6);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 2
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 2
    lv_obj_set_x(ui_Label7, -28);
    lv_obj_set_y(ui_Label7, 24);
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label7, "49.7");
    lv_obj_set_style_text_color(ui_Label7, lv_color_hex(0xF5F5F5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label8 = lv_label_create(ui_Panel6);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);   /// 2
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT);    /// 2
    lv_obj_set_x(ui_Label8, 30);
    lv_obj_set_y(ui_Label8, 20);
    lv_obj_set_align(ui_Label8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label8, "49.7");
    lv_obj_set_style_text_color(ui_Label8, lv_color_hex(0xF5F5F5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label9 = lv_label_create(ui_Panel6);
    lv_obj_set_width(ui_Label9, LV_SIZE_CONTENT);   /// 2
    lv_obj_set_height(ui_Label9, LV_SIZE_CONTENT);    /// 2
    lv_obj_set_x(ui_Label9, -16);
    lv_obj_set_y(ui_Label9, -29);
    lv_obj_set_align(ui_Label9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label9, "49.7");
    lv_obj_set_style_text_color(ui_Label9, lv_color_hex(0xF5F5F5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel3 = lv_obj_create(ui_data);
    lv_obj_set_width(ui_Panel3, 320);
    lv_obj_set_height(ui_Panel3, 80);
    lv_obj_set_x(ui_Panel3, 0);
    lv_obj_set_y(ui_Panel3, 60);
    lv_obj_set_align(ui_Panel3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel3, lv_color_hex(0xFE7370), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel3, 180, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image6 = lv_img_create(ui_Panel3);
    lv_img_set_src(ui_Image6, &ui_img_copy_png);
    lv_obj_set_width(ui_Image6, LV_SIZE_CONTENT);   /// 50
    lv_obj_set_height(ui_Image6, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(ui_Image6, 76);
    lv_obj_set_y(ui_Image6, -1);
    lv_obj_set_align(ui_Image6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image6, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label5 = lv_label_create(ui_Panel3);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label5, -21);
    lv_obj_set_y(ui_Label5, 1);
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "2025-4-23 16:37");
    lv_obj_set_style_text_color(ui_Label5, lv_color_hex(0xF5F5F5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button1 = lv_btn_create(ui_Screen3);
    lv_obj_set_width(ui_Button1, 150);
    lv_obj_set_height(ui_Button1, 60);
    lv_obj_set_x(ui_Button1, 90);
    lv_obj_set_y(ui_Button1, -65);
    lv_obj_set_align(ui_Button1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button1, lv_color_hex(0xF6FE00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Button1, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Button1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image13 = lv_img_create(ui_Button1);
    lv_img_set_src(ui_Image13, &ui_img_state_png);
    lv_obj_set_width(ui_Image13, LV_SIZE_CONTENT);   /// 40
    lv_obj_set_height(ui_Image13, LV_SIZE_CONTENT);    /// 40
    lv_obj_set_x(ui_Image13, -34);
    lv_obj_set_y(ui_Image13, -2);
    lv_obj_set_align(ui_Image13, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image13, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image13, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label15 = lv_label_create(ui_Button1);
    lv_obj_set_width(ui_Label15, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label15, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label15, 17);
    lv_obj_set_y(ui_Label15, 0);
    lv_obj_set_align(ui_Label15, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label15, "ON");
    lv_obj_set_style_text_color(ui_Label15, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label15, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Buletooth = lv_btn_create(ui_Screen3);
    lv_obj_set_width(ui_Buletooth, 150);
    lv_obj_set_height(ui_Buletooth, 60);
    lv_obj_set_x(ui_Buletooth, 90);
    lv_obj_set_y(ui_Buletooth, -135);
    lv_obj_set_align(ui_Buletooth, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Buletooth, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Buletooth, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Buletooth, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Buletooth, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Buletooth, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Buletooth, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_tooth = lv_img_create(ui_Buletooth);
    lv_img_set_src(ui_tooth, &ui_img_booth_png);
    lv_obj_set_width(ui_tooth, LV_SIZE_CONTENT);   /// 30
    lv_obj_set_height(ui_tooth, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_tooth, -33);
    lv_obj_set_y(ui_tooth, 0);
    lv_obj_set_align(ui_tooth, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_tooth, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_tooth, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_boothconnect = lv_label_create(ui_Buletooth);
    lv_obj_set_width(ui_boothconnect, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_boothconnect, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_boothconnect, 13);
    lv_obj_set_y(ui_boothconnect, 0);
    lv_obj_set_align(ui_boothconnect, LV_ALIGN_CENTER);
    lv_label_set_text(ui_boothconnect, "connect");

    ui_Panel4 = lv_obj_create(ui_Screen3);
    lv_obj_set_width(ui_Panel4, 150);
    lv_obj_set_height(ui_Panel4, 30);
    lv_obj_set_x(ui_Panel4, 90);
    lv_obj_set_y(ui_Panel4, -190);
    lv_obj_set_align(ui_Panel4, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Bar3 = lv_bar_create(ui_Panel4);
    lv_bar_set_value(ui_Bar3, 25, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_Bar3, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Bar3, 90);
    lv_obj_set_height(ui_Bar3, 20);
    lv_obj_set_x(ui_Bar3, -22);
    lv_obj_set_y(ui_Bar3, -1);
    lv_obj_set_align(ui_Bar3, LV_ALIGN_CENTER);

    ui_Label1 = lv_label_create(ui_Panel4);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, 50);
    lv_obj_set_y(ui_Label1, 0);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "25%");

    lv_obj_add_event_cb(ui_Screen3, ui_event_Screen3, LV_EVENT_ALL, NULL);

}
