// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.6
// Project name: SmartWatch

#include "../ui.h"

void ui_Screen6_screen_init(void)
{
    ui_Screen6 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen6, lv_color_hex(0x030303), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Calendar3 = lv_calendar_create(ui_Screen6);
    lv_calendar_set_today_date(ui_Calendar3, 2025, 5, 1);
    lv_calendar_set_showed_date(ui_Calendar3, 2025, 5);
    lv_obj_t * ui_Calendar3_header = lv_calendar_header_arrow_create(ui_Calendar3);
    lv_obj_set_width(ui_Calendar3, 180);
    lv_obj_set_height(ui_Calendar3, 220);
    lv_obj_set_x(ui_Calendar3, 85);
    lv_obj_set_y(ui_Calendar3, -110);
    lv_obj_set_align(ui_Calendar3, LV_ALIGN_CENTER);

    ui_Panel12 = lv_obj_create(ui_Screen6);
    lv_obj_set_width(ui_Panel12, 160);
    lv_obj_set_height(ui_Panel12, 220);
    lv_obj_set_x(ui_Panel12, -95);
    lv_obj_set_y(ui_Panel12, -110);
    lv_obj_set_align(ui_Panel12, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel12, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image17 = lv_img_create(ui_Panel12);
    lv_img_set_src(ui_Image17, &ui_img_1718491849);
    lv_obj_set_width(ui_Image17, LV_SIZE_CONTENT);   /// 140
    lv_obj_set_height(ui_Image17, LV_SIZE_CONTENT);    /// 140
    lv_obj_set_x(ui_Image17, 1);
    lv_obj_set_y(ui_Image17, -38);
    lv_obj_set_align(ui_Image17, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image17, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image17, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label20 = lv_label_create(ui_Panel12);
    lv_obj_set_width(ui_Label20, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label20, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label20, 0);
    lv_obj_set_y(ui_Label20, 42);
    lv_obj_set_align(ui_Label20, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label20, "WestCity-YOLO");

    ui_Label19 = lv_label_create(ui_Panel12);
    lv_obj_set_width(ui_Label19, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label19, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label19, 0);
    lv_obj_set_y(ui_Label19, 78);
    lv_obj_set_align(ui_Label19, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label19, "KunMing YMU");
    lv_obj_set_style_text_font(ui_Label19, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label18 = lv_label_create(ui_Panel12);
    lv_obj_set_width(ui_Label18, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label18, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label18, 17);
    lv_obj_set_y(ui_Label18, 95);
    lv_obj_set_align(ui_Label18, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label18, "863963777@qq.com");
    lv_obj_set_style_text_font(ui_Label18, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image18 = lv_img_create(ui_Panel12);
    lv_img_set_src(ui_Image18, &ui_img_youjian_png);
    lv_obj_set_width(ui_Image18, LV_SIZE_CONTENT);   /// 18
    lv_obj_set_height(ui_Image18, LV_SIZE_CONTENT);    /// 18
    lv_obj_set_x(ui_Image18, -54);
    lv_obj_set_y(ui_Image18, 96);
    lv_obj_set_align(ui_Image18, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image18, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image18, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image19 = lv_img_create(ui_Panel12);
    lv_img_set_src(ui_Image19, &ui_img_chenshi_png);
    lv_obj_set_width(ui_Image19, LV_SIZE_CONTENT);   /// 18
    lv_obj_set_height(ui_Image19, LV_SIZE_CONTENT);    /// 18
    lv_obj_set_x(ui_Image19, -54);
    lv_obj_set_y(ui_Image19, 80);
    lv_obj_set_align(ui_Image19, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image19, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image19, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image20 = lv_img_create(ui_Panel12);
    lv_img_set_src(ui_Image20, &ui_img_dingwei_png);
    lv_obj_set_width(ui_Image20, LV_SIZE_CONTENT);   /// 18
    lv_obj_set_height(ui_Image20, LV_SIZE_CONTENT);    /// 18
    lv_obj_set_x(ui_Image20, -56);
    lv_obj_set_y(ui_Image20, 63);
    lv_obj_set_align(ui_Image20, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image20, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image20, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label21 = lv_label_create(ui_Panel12);
    lv_obj_set_width(ui_Label21, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label21, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label21, -19);
    lv_obj_set_y(ui_Label21, 62);
    lv_obj_set_align(ui_Label21, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label21, "YunNan");
    lv_obj_set_style_text_font(ui_Label21, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image26 = lv_img_create(ui_Panel12);
    lv_img_set_src(ui_Image26, &ui_img_671965521);
    lv_obj_set_width(ui_Image26, LV_SIZE_CONTENT);   /// 30
    lv_obj_set_height(ui_Image26, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_Image26, -56);
    lv_obj_set_y(ui_Image26, 15);
    lv_obj_set_align(ui_Image26, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image26, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image26, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel17 = lv_obj_create(ui_Screen6);
    lv_obj_set_width(ui_Panel17, 350);
    lv_obj_set_height(ui_Panel17, 180);
    lv_obj_set_x(ui_Panel17, 0);
    lv_obj_set_y(ui_Panel17, 100);
    lv_obj_set_align(ui_Panel17, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel17, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image25 = lv_img_create(ui_Panel17);
    lv_img_set_src(ui_Image25, &ui_img_zzz_color_png);
    lv_obj_set_width(ui_Image25, LV_SIZE_CONTENT);   /// 30
    lv_obj_set_height(ui_Image25, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_Image25, -130);
    lv_obj_set_y(ui_Image25, 35);
    lv_obj_set_align(ui_Image25, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image25, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image25, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image24 = lv_img_create(ui_Panel17);
    lv_img_set_src(ui_Image24, &ui_img_smiling_face_with_hearts_color_png);
    lv_obj_set_width(ui_Image24, LV_SIZE_CONTENT);   /// 31
    lv_obj_set_height(ui_Image24, LV_SIZE_CONTENT);    /// 31
    lv_obj_set_x(ui_Image24, -130);
    lv_obj_set_y(ui_Image24, 0);
    lv_obj_set_align(ui_Image24, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image24, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image24, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image21 = lv_img_create(ui_Panel17);
    lv_img_set_src(ui_Image21, &ui_img_hello_png);
    lv_obj_set_width(ui_Image21, LV_SIZE_CONTENT);   /// 35
    lv_obj_set_height(ui_Image21, LV_SIZE_CONTENT);    /// 35
    lv_obj_set_x(ui_Image21, -130);
    lv_obj_set_y(ui_Image21, -70);
    lv_obj_set_align(ui_Image21, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image21, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image21, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image23 = lv_img_create(ui_Panel17);
    lv_img_set_src(ui_Image23, &ui_img_party_popper_color_png);
    lv_obj_set_width(ui_Image23, LV_SIZE_CONTENT);   /// 30
    lv_obj_set_height(ui_Image23, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_Image23, -130);
    lv_obj_set_y(ui_Image23, 70);
    lv_obj_set_align(ui_Image23, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image23, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image23, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image22 = lv_img_create(ui_Panel17);
    lv_img_set_src(ui_Image22, &ui_img_hundred_points_color_png);
    lv_obj_set_width(ui_Image22, LV_SIZE_CONTENT);   /// 30
    lv_obj_set_height(ui_Image22, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_Image22, -130);
    lv_obj_set_y(ui_Image22, -35);
    lv_obj_set_align(ui_Image22, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image22, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image22, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label22 = lv_label_create(ui_Panel17);
    lv_obj_set_width(ui_Label22, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label22, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label22, -30);
    lv_obj_set_y(ui_Label22, -70);
    lv_obj_set_align(ui_Label22, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label22, " Hi, Im @westcity-YOLO");

    ui_Label23 = lv_label_create(ui_Panel17);
    lv_obj_set_width(ui_Label23, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label23, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label23, 30);
    lv_obj_set_y(ui_Label23, -35);
    lv_obj_set_align(ui_Label23, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label23, "I'm interested in linux,RTOS,ML,DL,LLM");

    ui_Label24 = lv_label_create(ui_Panel17);
    lv_obj_set_width(ui_Label24, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label24, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label24, -3);
    lv_obj_set_y(ui_Label24, 0);
    lv_obj_set_align(ui_Label24, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label24, " I'm looking to collaborate on ...");

    ui_Label25 = lv_label_create(ui_Panel17);
    lv_obj_set_width(ui_Label25, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label25, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label25, -42);
    lv_obj_set_y(ui_Label25, 35);
    lv_obj_set_align(ui_Label25, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label25, " How to reach me ... ");

    ui_Label26 = lv_label_create(ui_Panel17);
    lv_obj_set_width(ui_Label26, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label26, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label26, -25);
    lv_obj_set_y(ui_Label26, 70);
    lv_obj_set_align(ui_Label26, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label26, "I'm currently learning ...");

    ui_Label27 = lv_label_create(ui_Screen6);
    lv_obj_set_width(ui_Label27, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label27, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label27, 15);
    lv_obj_set_y(ui_Label27, 207);
    lv_obj_set_align(ui_Label27, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label27, "https://github.com/westcity-YOLO");
    lv_obj_set_style_text_color(ui_Label27, lv_color_hex(0x00ECFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label27, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label27, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image27 = lv_img_create(ui_Screen6);
    lv_img_set_src(ui_Image27, &ui_img_lianjie_png);
    lv_obj_set_width(ui_Image27, LV_SIZE_CONTENT);   /// 25
    lv_obj_set_height(ui_Image27, LV_SIZE_CONTENT);    /// 25
    lv_obj_set_x(ui_Image27, -101);
    lv_obj_set_y(ui_Image27, 208);
    lv_obj_set_align(ui_Image27, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image27, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image27, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_Screen6, ui_event_Screen6, LV_EVENT_ALL, NULL);

}
