// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.6
// Project name: SmartWatch

#ifndef _SMARTWATCH_UI_H
#define _SMARTWATCH_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"


// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
void ui_event_Screen1(lv_event_t * e);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Arc1;
extern lv_obj_t * ui_Arc3;
extern lv_obj_t * ui_Arc7;
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_Label13;
extern lv_obj_t * ui_Label11;
extern lv_obj_t * ui_Image9;
extern lv_obj_t * ui_Image10;
extern lv_obj_t * ui_Image11;
extern lv_obj_t * ui_Image12;
extern lv_obj_t * ui_Label12;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_Label14;
// CUSTOM VARIABLES

// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
void ui_event_Screen2(lv_event_t * e);
extern lv_obj_t * ui_Screen2;
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_Chart2;
extern lv_obj_t * ui_Panel5;
extern lv_obj_t * ui_Image4;
extern lv_obj_t * ui_Panel8;
extern lv_obj_t * ui_Image3;
// CUSTOM VARIABLES

// SCREEN: ui_Screen3
void ui_Screen3_screen_init(void);
void ui_event_Screen3(lv_event_t * e);
extern lv_obj_t * ui_Screen3;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_majia;
extern lv_obj_t * ui_data;
extern lv_obj_t * ui_Panel7;
extern lv_obj_t * ui_Image2;
extern lv_obj_t * ui_Image5;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_Panel6;
extern lv_obj_t * ui_Image7;
extern lv_obj_t * ui_Image8;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_Label9;
extern lv_obj_t * ui_Panel3;
extern lv_obj_t * ui_Image6;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_Image13;
extern lv_obj_t * ui_Label15;
extern lv_obj_t * ui_Buletooth;
extern lv_obj_t * ui_tooth;
extern lv_obj_t * ui_boothconnect;
extern lv_obj_t * ui_Panel4;
extern lv_obj_t * ui_Bar3;
extern lv_obj_t * ui_Label1;
// CUSTOM VARIABLES

// SCREEN: ui_Screen4
void ui_Screen4_screen_init(void);
void ui_event_Screen4(lv_event_t * e);
extern lv_obj_t * ui_Screen4;
extern lv_obj_t * ui_Button2;
extern lv_obj_t * ui_Button3;
extern lv_obj_t * ui_Button4;
extern lv_obj_t * ui_Image16;
extern lv_obj_t * ui_Label17;
extern lv_obj_t * ui_Button5;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Image15;
extern lv_obj_t * ui_Bar1;
extern lv_obj_t * ui_Panel10;
extern lv_obj_t * ui_Panel11;
extern lv_obj_t * ui_Panel13;
extern lv_obj_t * ui_Panel14;
extern lv_obj_t * ui_Panel15;
extern lv_obj_t * ui_Panel16;
void ui_event_ImgButton3(lv_event_t * e);
extern lv_obj_t * ui_ImgButton3;
extern lv_obj_t * ui_Bar4;
extern lv_obj_t * ui_Label16;
// CUSTOM VARIABLES

// SCREEN: ui_Screen5
void ui_Screen5_screen_init(void);
void ui_event_Screen5(lv_event_t * e);
extern lv_obj_t * ui_Screen5;
void ui_event_Panel9(lv_event_t * e);
extern lv_obj_t * ui_Panel9;
extern lv_obj_t * ui_Image14;
extern lv_obj_t * ui_ImgButton1;
extern lv_obj_t * ui_ImgButton2;
// CUSTOM VARIABLES

// SCREEN: ui_Screen6
void ui_Screen6_screen_init(void);
void ui_event_Screen6(lv_event_t * e);
extern lv_obj_t * ui_Screen6;
extern lv_obj_t * ui_Calendar3;
extern lv_obj_t * ui_Panel12;
extern lv_obj_t * ui_Image17;
extern lv_obj_t * ui_Label20;
extern lv_obj_t * ui_Label19;
extern lv_obj_t * ui_Label18;
extern lv_obj_t * ui_Image18;
extern lv_obj_t * ui_Image19;
extern lv_obj_t * ui_Image20;
extern lv_obj_t * ui_Label21;
extern lv_obj_t * ui_Image26;
extern lv_obj_t * ui_Panel17;
extern lv_obj_t * ui_Image25;
extern lv_obj_t * ui_Image24;
extern lv_obj_t * ui_Image21;
extern lv_obj_t * ui_Image23;
extern lv_obj_t * ui_Image22;
extern lv_obj_t * ui_Label22;
extern lv_obj_t * ui_Label23;
extern lv_obj_t * ui_Label24;
extern lv_obj_t * ui_Label25;
extern lv_obj_t * ui_Label26;
extern lv_obj_t * ui_Label27;
extern lv_obj_t * ui_Image27;
// CUSTOM VARIABLES

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_zuji_png);    // assets/zuji.png
LV_IMG_DECLARE(ui_img_shandian_png);    // assets/shandian.png
LV_IMG_DECLARE(ui_img_kaluli_png);    // assets/kaluli.png
LV_IMG_DECLARE(ui_img_heartsmall_png);    // assets/heartsmall.png
LV_IMG_DECLARE(ui_img_duoyun_png);    // assets/duoyun.png
LV_IMG_DECLARE(ui_img_heart_png);    // assets/heart.png
LV_IMG_DECLARE(ui_img_shq2_png);    // assets/ShQ2.png
LV_IMG_DECLARE(ui_img_812553787);    // assets/majia(1).png
LV_IMG_DECLARE(ui_img_airpump_png);    // assets/Airpump.png
LV_IMG_DECLARE(ui_img_airpressure_png);    // assets/Airpressure.png
LV_IMG_DECLARE(ui_img_zuobiao_png);    // assets/zuobiao.png
LV_IMG_DECLARE(ui_img_lifang_png);    // assets/lifang.png
LV_IMG_DECLARE(ui_img_copy_png);    // assets/copy.png
LV_IMG_DECLARE(ui_img_state_png);    // assets/state.png
LV_IMG_DECLARE(ui_img_booth_png);    // assets/booth.png
LV_IMG_DECLARE(ui_img_wifi_png);    // assets/wifi.png
LV_IMG_DECLARE(ui_img_bluetooth_png);    // assets/Bluetooth.png
LV_IMG_DECLARE(ui_img_543043862);    // assets/majia(2).png
LV_IMG_DECLARE(ui_img_1726297279_195593_png);    // assets/1726297279_195593.png
LV_IMG_DECLARE(ui_img_guaduan_png);    // assets/guaduan.png
LV_IMG_DECLARE(ui_img_jieting_png);    // assets/jieting.png
LV_IMG_DECLARE(ui_img_1718491849);    // assets/head(1).png
LV_IMG_DECLARE(ui_img_youjian_png);    // assets/youjian.png
LV_IMG_DECLARE(ui_img_chenshi_png);    // assets/chenshi.png
LV_IMG_DECLARE(ui_img_dingwei_png);    // assets/dingwei.png
LV_IMG_DECLARE(ui_img_671965521);    // assets/github-circle.png
LV_IMG_DECLARE(ui_img_zzz_color_png);    // assets/zzz_color.png
LV_IMG_DECLARE(ui_img_smiling_face_with_hearts_color_png);    // assets/smiling_face_with_hearts_color.png
LV_IMG_DECLARE(ui_img_hello_png);    // assets/hello.png
LV_IMG_DECLARE(ui_img_party_popper_color_png);    // assets/party_popper_color.png
LV_IMG_DECLARE(ui_img_hundred_points_color_png);    // assets/hundred_points_color.png
LV_IMG_DECLARE(ui_img_lianjie_png);    // assets/lianjie.png

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
